CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE seats (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       event_id BIGINT NOT NULL REFERENCES events(id),
                       seat_number VARCHAR(30) NOT NULL,
                       status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
                       CONSTRAINT chk_seat_status
                           CHECK (status IN ('AVAILABLE', 'HELD', 'RESERVED')),
                       CONSTRAINT uq_event_seat
                           UNIQUE (event_id, seat_number)
);

CREATE TABLE reservations (
                              id UUID PRIMARY KEY,
                              user_id VARCHAR(100) NOT NULL,
                              status VARCHAR(20) NOT NULL,
                              idempotency_key VARCHAR(200) NOT NULL,
                              request_hash VARCHAR(64) NOT NULL,
                              created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                              expires_at TIMESTAMPTZ,
                              CONSTRAINT uq_user_idempotency
                                  UNIQUE (user_id, idempotency_key)
);

CREATE TABLE reservation_seats (
                                   reservation_id UUID NOT NULL
                                       REFERENCES reservations(id),
                                   seat_id BIGINT NOT NULL
                                       REFERENCES seats(id),
                                   PRIMARY KEY (reservation_id, seat_id)
);

CREATE INDEX idx_seats_event_status
    ON seats(event_id, status);

CREATE INDEX idx_reservations_user_status
    ON reservations(user_id, status);